# Generated by Django 4.0.3 on 2022-06-05 11:42

import Admin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='Days2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=Admin.models.filepath),
        ),
    ]
