# Generated by Django 4.0.3 on 2022-06-05 11:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_department_days2_alter_department_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='rate',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
