# Generated by Django 4.0.3 on 2022-06-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_alter_department_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
