# Generated by Django 4.0.3 on 2022-06-09 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_department_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='Doc',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
    ]
