# Generated by Django 4.0.3 on 2022-06-09 22:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_alter_patient_national_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='National_num',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(14)]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Phone',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(11), django.core.validators.MaxValueValidator(11)]),
        ),
    ]
