# Generated by Django 4.0.3 on 2022-06-10 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_alter_patient_national_num_alter_patient_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='BirthDay',
            field=models.DateField(null=True),
        ),
    ]
