# Generated by Django 4.0.3 on 2022-06-13 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_alter_patient_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='National_num',
            field=models.CharField(max_length=255),
        ),
    ]
