# Generated by Django 4.0.3 on 2022-06-13 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_alter_ticket_enddate_alter_ticket_startdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='Feedback',
            new_name='FeedBack',
        ),
    ]
