# Generated by Django 4.0.3 on 2022-06-27 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_alter_ticket_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept', to='Admin.department'),
        ),
    ]
